import type { Metadata } from "next";
import Link from "next/link";
import { FileText } from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Service – LinkForge",
  description: "LinkForge Terms of Service. Free tools for LinkedIn users — learn how you can use our platform.",
};

export default function TermsPage() {
  const lastUpdated = "January 2025";

  return (
    <div className="min-h-screen bg-gray-50 py-16 px-4">
      <div className="max-w-3xl mx-auto">
        <div className="text-center mb-10">
          <div className="w-14 h-14 bg-gradient-to-br from-[#0A66C2] to-[#004182] rounded-2xl flex items-center justify-center mx-auto mb-4">
            <FileText className="w-7 h-7 text-white" />
          </div>
          <h1 className="text-4xl font-bold text-gray-900 mb-3">Terms of Service</h1>
          <p className="text-gray-500 text-sm">Last updated: {lastUpdated}</p>
        </div>

        <div className="bg-green-50 border border-green-200 rounded-2xl p-6 mb-8">
          <h2 className="font-bold text-green-900 mb-2">The Short Version</h2>
          <p className="text-green-800 text-sm leading-relaxed">
            LinkForge is a free platform. Use it to improve your LinkedIn presence. Don't misuse it, don't violate LinkedIn's own terms, and understand that we provide tools "as is" without warranties.
          </p>
        </div>

        <div className="bg-white rounded-2xl border border-gray-200 shadow-sm divide-y divide-gray-100">
          {[
            {
              title: "1. Acceptance of Terms",
              content: `By accessing and using LinkForge ("the Platform", "we", "us"), you accept and agree to be bound by these Terms of Service. If you do not agree, please discontinue use of the platform immediately.`,
            },
            {
              title: "2. Description of Service",
              content: `LinkForge provides free web-based tools designed to help users optimize their LinkedIn profiles, create content, and advance their careers. The platform includes, but is not limited to:

• Profile analysis and optimization tools
• Content generation tools for LinkedIn posts, messages, and headlines
• Career management tools including job tracking and CV generation
• Utility tools for formatting, character counting, and readability checking

All tools are provided free of charge with no subscription or account required.`,
            },
            {
              title: "3. Free to Use",
              content: `LinkForge is completely free. You do not need to:

• Create an account
• Provide payment information
• Subscribe to any plan
• Register your email

We reserve the right to add optional premium features in the future, but existing free features will remain free.`,
            },
            {
              title: "4. Acceptable Use",
              content: `You agree to use LinkForge only for lawful purposes and in accordance with these Terms. You agree NOT to:

• Use the platform to generate spam, misleading, or deceptive content
• Use generated content in ways that violate LinkedIn's Terms of Service
• Attempt to reverse-engineer, hack, or interfere with the platform
• Use automated scripts or bots to access the platform
• Use the tools to harass, defame, or harm other individuals
• Violate any applicable local, national, or international laws`,
            },
            {
              title: "5. LinkedIn Terms of Service",
              content: `LinkForge is an independent tool platform and is not affiliated with, endorsed by, or partnered with LinkedIn Corporation or Microsoft.

When using content generated by LinkForge on LinkedIn, you remain solely responsible for complying with LinkedIn's own Terms of Service, User Agreement, and Community Guidelines. LinkForge makes no representations about whether specific use cases comply with LinkedIn's policies.

LinkedIn® is a registered trademark of LinkedIn Corporation.`,
            },
            {
              title: "6. Content Ownership",
              content: `Content you input into LinkForge tools remains yours. Content generated by our tools is provided for your use — you own and are responsible for any generated content you publish or distribute.

We do not claim ownership over any content you create using our tools.`,
            },
            {
              title: "7. Disclaimer of Warranties",
              content: `LinkForge is provided "as is" and "as available" without any warranties of any kind, express or implied, including but not limited to:

• Warranties of merchantability or fitness for a particular purpose
• Guarantees that the platform will be error-free or uninterrupted
• Guarantees about the accuracy or completeness of generated content
• Guarantees about career outcomes from using our tools

We do not guarantee that using our tools will result in job offers, improved LinkedIn performance, or any other specific outcome.`,
            },
            {
              title: "8. Limitation of Liability",
              content: `To the maximum extent permitted by law, LinkForge and its creators shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of employment, missed opportunities, or any reliance on content generated by the platform.`,
            },
            {
              title: "9. Data and Privacy",
              content: `Your privacy is important to us. Please review our Privacy Policy to understand how we handle data. In summary: we do not collect or store your personal data on any server. All data is stored locally in your browser.`,
            },
            {
              title: "10. Modifications to Terms",
              content: `We reserve the right to modify these Terms at any time. Changes will be effective immediately upon posting. Continued use of the platform after changes constitutes acceptance of the new Terms.`,
            },
            {
              title: "11. Governing Law",
              content: `These Terms shall be governed by and construed in accordance with applicable law. Any disputes arising from use of this platform shall be resolved through good-faith negotiation before pursuing legal remedies.`,
            },
            {
              title: "12. Contact",
              content: `If you have questions about these Terms, please contact us at iamaaadil@gmail.com or visit our Contact page.`,
            },
          ].map((section, i) => (
            <div key={i} className="p-6">
              <h2 className="text-lg font-bold text-gray-900 mb-3">{section.title}</h2>
              <div className="text-gray-600 text-sm leading-relaxed whitespace-pre-line">{section.content}</div>
            </div>
          ))}
        </div>

        <div className="mt-8 text-center">
          <p className="text-gray-500 text-sm">
            Questions?{" "}
            <Link href="/contact" className="text-[#0A66C2] hover:underline">
              Contact us
            </Link>{" "}
            or read our{" "}
            <Link href="/privacy" className="text-[#0A66C2] hover:underline">
              Privacy Policy
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
}
